### ISSUE TITLE
REP instruction only performs one iteration

### ISSUE THREAD

**Issue by gyorokpeter** [JonathanSalwan/Triton#472] opened 2017-01-19 08:14 UTC
```python
>>> from triton import *
>>> setArchitecture(ARCH.X86)
>>> setConcreteRegisterValue(Register(REG.ECX,3))
>>> inst = Instruction('\xf3\xa4')
>>> processing(inst)
True
>>> inst
0: rep movsb byte ptr es:[edi], byte ptr [esi]
>>> getConcreteRegisterValue(REG.ECX)
2L
>>> inst.getLoadAccess()
[([@0x0]:8 bv[7..0], ((_ extract 7 0) (_ bv0 8)))]
```

There should be a way to process all iterations with a single call and get all the load/store accesses on the same instruction object.

**Comment by JonathanSalwan** [comment] 2017-01-19 08:47
Mmmmh i don't know. e.g: classical debuggers like gdb or even Pin do the same behavior.

**Comment by gyorokpeter** [comment] 2017-01-20 07:56
This is only a matter of convenience. I can work around this in user code, but then I'm only fixing the parts I need (by adding the load/store accesses and setting ECX to zero).

**Comment by JonathanSalwan** [comment] 2017-01-24 19:13
I close this issue because I will keep the current design.

**Closed by JonathanSalwan** 2017-01-24 19:13 UTC
Labels: Question

**Comment by gyorokpeter** [comment] 2017-01-25 08:27
If I make a patch with my current implementation will you accept it?

**Comment by JonathanSalwan** [comment] 2017-01-25 09:04
is your patch will process all iterations when `processing()` is called?

**Comment by gyorokpeter** [comment] 2017-01-25 23:31
No, I would add an alternative function to do that (e.g. "processingRep").

**Comment by JonathanSalwan** [comment] 2017-01-26 08:59
Mmmh, the problem is that `processingRep` is specific to x86.

**Comment by mermakov** [comment] 2017-05-03 17:26
Hello!

Sorry to bump this up, but I recently ran into a somewhat related issue. Not sure if it's actually a Triton issue, but rather client-side.

For REP** prefixes if CX was 0 before the instruction, it will not perform the instruction at all. Current implementation in x86Semantics creates all necessary SymbolicExpressions and only then calls controlFlow_s to check REP-related stuff. This creates extra expressions and can propagate taint incorrectly.

Hope this helps!

**Comment by JonathanSalwan** [comment] 2017-05-04 15:13
@mermakov, indeed, can you open a new issue plz?

**Comment by mermakov** [comment] 2017-05-04 15:57
@JonathanSalwan sure, done. See #530
