### ISSUE TITLE
How to copy TritonContext?

### ISSUE THREAD

**Issue by alazymechnaic** [JonathanSalwan/Triton#1254] opened 2023-06-15 03:03 UTC
I want to save the state of the TritonContext at a certain time, but the deepcopy function doesn't work, I wonder if there is a solution

**Comment by SweetVishnya** [comment] 2023-06-15 05:49
Seems to be a duplicate of #532 that is not implemented.

**Comment by JonathanSalwan** [comment] 2023-08-04 07:51
Yep it's not implemented yet. Dupe of #532

**Closed by JonathanSalwan** 2023-08-04 07:51 UTC
