### ISSUE TITLE
Decrease register value update overhead in Pin tracer

### ISSUE THREAD

**Issue by mermakov** [JonathanSalwan/Triton#376] opened 2016-08-15 17:29 UTC
Hello!

I have been using Pin + Triton on programs and considering possible performance issues which arise with large traces.

The one thing I see as important is register update that happens before every instruction. As I understand it sets real values to be used in `buildSemantics`. However, it updates all registers supported in Pin and Triton, whereas most instructions do not use all these registers.

I was wondering if there was a way to identify all the necessary registers and only update those relevant to the instruction. I'm considering mainly symbolic trace and I am not sure this approach will not break other Triton functionality (probably will break snapshots?).

Does capstone correctly identify all relevant registers (for instance, some instructions may have hard-coded behavior to use a specific register regardless of the opcode)? If so, it might be possible to use triton::arch::Instruction::operands vector?

Just for some numbers on the impact of register update: two short examples take 9 and 17 seconds to run through Pin with basic script logic; with `tracer::pintool::context::setupContextRegister(tritonInst, ctx);` commented out these numbers drop to 5 and 10 seconds respectively (so the overhead is not constant).

I apologize for giving a mixed report/suggestion/question instead of a proper issue, but I think it might help Triton performance.

**Comment by JonathanSalwan** [comment] 2016-08-15 17:53
Hey,

> The one thing I see as important is register update that happens before every instruction. As I understand it sets real values to be used in buildSemantics. However, it updates all registers supported in Pin and Triton, whereas most instructions do not use all these registers.

True.

> I was wondering if there was a way to identify all the necessary registers and only update those relevant to the instruction. I'm considering mainly symbolic trace and I am not sure this approach will not break other Triton functionality (probably will break snapshots?).

The problem is that a lots of instructions use implicit registers / memory effects (e.g: cpuid, lodsb, imul, idiv etc). So, we cannot predict what implicit registers/memory will be use via the disassembly engine. To know it, we need the instruction semantics and to create good instruction semantics we need valid concrete values...

> I apologize for giving a mixed report/suggestion/question instead of a proper issue, but I think it might help Triton performance.

Don't worry it's a nice thread.

I think what we can try is to only set once (at start) all registers values. Then, let Triton update its own context and when there is a difference between the Pin's RIP value and the Triton's RIP value (which is common), we update all context registers and so on.

What do you think?

**Comment by 0ca** [comment] 2016-08-15 18:10
> I think what we can try is to only set once (at start) all registers values. Then, let Triton update its own context and when there is a difference between the Pin's RIP value and the Triton's RIP value (which is common), we update all context registers and so on.

Hi, but then you still need in every instruction to know all the registers to compare the real context with the "emulation", right?

I was thinking about this same problem and I think it would be very cool if we could set in libtriton a function to have direct access to memory and registers. For example if you are tracing with pin, then you could provide to libtriton a function that is getting the registers using the PIN_GetContextRegval, for example this function: https://github.com/JonathanSalwan/Triton/blob/master/src/tracer/pin/context.cpp#L30
And access to the memory with another function that is just reading the program memory.

So then you wouldn't need to update the context in every instruction because when libtriton need to use any register or memory is going to use the functions we provided it and have direct access to registers and memory.

Would it be possible to do this? Or there is some details I'm missing?

Another detail about this:
With PIN is very easy to get the memory accessed by a instruction with the `IARG_MEMORYREAD_EA `, `IARG_MEMORYWRITE_EA`. But in dynamo rio you don't have something like this so it requires some extrawork. And think about do the same with IDA, you would need to preprocess the instruction to get the memory accessed, then update the context and reprocess the instruction. But if we could provide libtriton with a function using the IDA api to get the registers and memory this would be very easy ;)

**Comment by mermakov** [comment] 2016-08-15 18:10
> The problem is that a lots of instructions use implicit registers / memory effects (e.g: cpuid, lodsb, imul, idiv etc). So, we cannot predict what implicit registers/memory will be use via the disassembly engine. To know it, we need the instruction semantics and to create good instruction semantics we need valid concrete values...

Yes, that was my expected problem.

> I think what we can try is to only set once (at start) all registers values. Then, let Triton update its own context and when there is a difference between the Pin's RIP value and the Triton's RIP value (which is common), we update all context registers and so on.

I am not sure I fully understand the part about the IP value. Do you mean branching points are enough to identify that something went wrong? Something can be wrong in the beginning of a long linear sequence of instructions and carried all the way to a branching point. Identifying where exactly the symbolic trace is invalid does not seem to be feasible. Sorry if I got your idea wrong.

If identifying all implicit registers is not possible, there will probably be problems with parts of code where instrumentation was disabled (like image blacklist) because returning from these parts will definitely break register values.

Perhaps the most safe solution is to identify common instructions which do not have implicit dependencies and optimize context update for them?

**Comment by JonathanSalwan** [comment] 2016-08-15 19:06
> Perhaps the most safe solution is to identify common instructions which do not have implicit dependencies and optimize context update for them?

This solution doesn't really scale and it's a bit of boring to maintain these kind of tables. I think the best solution is what @0ca said. In fact, we already have this kind of [callback](http://triton.quarkslab.com/documentation/doxygen/py_CALLBACK_page.html) for memory hit. We can, do the same thing with registers read. Then, tracers may use these callbacks to update concrete values.

**Comment by mermakov** [comment] 2016-08-16 10:59
> This solution doesn't really scale and it's a bit of boring to maintain these kind of tables. I think the best solution is what @0ca said. In fact, we already have this kind of callback for memory hit. We can, do the same thing with registers read. Then, tracers may use these callbacks to update concrete values.

I haven't encountered this callback while studying Triton, but it seems like doing the same trick for registers should work perfectly - retrieve the value only when it's actually needed. Great idea!

**Comment by enzet** [comment] 2016-08-16 19:08
> I was thinking about this same problem and I think it would be very cool if we could set in libtriton a function to have direct access to memory and registers. For example if you are tracing with pin, then you could provide to libtriton a function that is getting the registers using the `PIN_GetContextRegval`...

I think, this is a good idea. And it works well for dynamic instrumentation approach (for tools like Pin and DynamoRIO). But in case of static instrumentation, it's pretty hard to get access to registers from instrumentation code at runtime. If I want to write a tracer based on static instrumentation (e.g. binary patching in Dyninst) I should use current approach.

Dyninst works well with Triton library for now. So, I wish current approach with concrete value transfered to tracer will be supported as well, because static instrumentation is pretty helpful in some cases.

**Comment by JonathanSalwan** [comment] 2016-08-21 12:16
Ok so, there is now two callbacks:

- **CALLBACK.GET_CONCRETE_MEMORY_VALUE**
The callback takes as unique argument a MemoryAccess. Callbacks will be called each time that the Triton library will need a concrete memory value. The callback must return nothing.

- **CALLBACK.GET_CONCRETE_REGISTER_VALUE**
The callback takes as unique argument a Register. Callbacks will be called each time that the Triton library will need a concrete register value. The callback must return nothing.

Take a look to this [example](https://github.com/JonathanSalwan/Triton/blob/dev-376/src/examples/pin/callback_concrete_needs.py) to see what is going on.

```console
$ ./triton ./src/examples/pin/callback_concrete_needs.py /usr/bin/id | less
Need concrete register value: ebp:32 bv[31..0]
Need concrete register value: ebp:32 bv[31..0]
Processing instruction at 402310: xor ebp, ebp 

Need concrete register value: rdx:64 bv[63..0]
Processing instruction at 402312: mov r9, rdx 

Need concrete register value: rsp:64 bv[63..0]
Need concrete memory value: [@0x7ffcf27ad120]:64 bv[63..0]
Need concrete register value: rsp:64 bv[63..0]
Processing instruction at 402315: pop rsi 

Processing instruction at 402316: mov rdx, rsp 

Processing instruction at 402319: and rsp, 0xfffffffffffffff0 

Need concrete register value: rax:64 bv[63..0]
Processing instruction at 40231d: push rax 

Processing instruction at 40231e: push rsp 

Processing instruction at 40231f: mov r8, 0x405b20 

Processing instruction at 402326: mov rcx, 0x405ab0 

Processing instruction at 40232d: mov rdi, 0x401900 

Processing instruction at 402334: call 0x4016d0 

Need concrete memory value: [@0x609110]:64 bv[63..0]
Processing instruction at 4016d0: jmp qword ptr [rip + 0x207a3a] 

Need concrete register value: r14:64 bv[63..0]
Processing instruction at 7f2e9dd06530: push r14 

Need concrete register value: r13:64 bv[63..0]
Processing instruction at 7f2e9dd06532: push r13 

Need concrete register value: r12:64 bv[63..0]
Processing instruction at 7f2e9dd06534: push r12 

Processing instruction at 7f2e9dd06536: push rbp 

Processing instruction at 7f2e9dd06537: mov rbp, rcx

Need concrete register value: rbx:64 bv[63..0]
Processing instruction at 7f2e9dd0653a: push rbx 

Processing instruction at 7f2e9dd0653b: sub rsp, 0x90 

Need concrete memory value: [@0x7f2e9e07cf08]:64 bv[63..0]
Processing instruction at 7f2e9dd06542: mov rax, qword ptr [rip + 0x3769bf] 

Processing instruction at 7f2e9dd06549: mov qword ptr [rsp + 0x18], rdi 

Processing instruction at 7f2e9dd0654e: mov dword ptr [rsp + 0x14], esi 

Processing instruction at 7f2e9dd06552: mov qword ptr [rsp + 8], rdx 

Processing instruction at 7f2e9dd06557: test rax, rax 

Processing instruction at 7f2e9dd0655a: je 0x7f2e9dd06627 

Processing instruction at 7f2e9dd06627: xor edx, edx 

Processing instruction at 7f2e9dd06629: jmp 0x7f2e9dd06569 

Processing instruction at 7f2e9dd06569: lea rax, qword ptr [rip + 0x376b50] 

Processing instruction at 7f2e9dd06570: test r9, r9 

Processing instruction at 7f2e9dd06573: mov dword ptr [rax], edx 

Processing instruction at 7f2e9dd06575: je 0x7f2e9dd06583 

Processing instruction at 7f2e9dd06577: xor edx, edx 

Processing instruction at 7f2e9dd06579: xor esi, esi 
[...]
```

As you can see, when a value is fetched for the first time, callbacks are called. Then, when an instruction uses values already known (SSA form with a deep > 1), Triton don't need to know their concrete value because it uses the last symbolic expression assigned (SSA-based).

**Comment by JonathanSalwan** [comment] 2016-08-22 11:59
The pintool now uses these previous callbacks to synch its context with Triton. So, I removed the setupContext [[1](https://github.com/JonathanSalwan/Triton/commit/02e42994df447d3cd9ed12d9b371123b913e252e#diff-b2dcdbbd4e8690bfd2ca1ddbdeabf0dfL568), [2](https://github.com/JonathanSalwan/Triton/commit/02e42994df447d3cd9ed12d9b371123b913e252e#diff-46edbd9de8b11a0439e16b6007bdf3faL470)] at each processed instruction. Also, there is no need to provide memory read/write via ``

**Comment by JonathanSalwan** [comment] 2016-08-22 12:25
Mmmh, it seems that there are still some [issues](https://travis-ci.org/JonathanSalwan/Triton/builds/154127188) by removing `IARG_MEMORYWRITE_EA` and `IARG_MEMORYREAD_EA`. I will investigate this.

**Comment by JonathanSalwan** [comment] 2016-08-27 20:51
Merged into master.

**Closed by JonathanSalwan** 2016-08-27 20:51 UTC
Labels: Enhancement, libTriton, Pintool

**Comment by mermakov** [comment] 2016-08-27 21:13
Hello!

Sorry for the lack of attention, was away on holiday.

Thank you for your work, this looks great! I'll be sure to test it out with our examples.
