### ISSUE TITLE
Garbage collector of unused AST nodes and SE

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#319] opened 2016-03-14 18:54 UTC
To gain memory, we must implement a GC which will collect and delete unused AST nodes and symbolic expressions during the execution.

Protip: custom inc/dec ref or shared_ptr

**Comment by mermakov** [comment] 2016-08-04 19:05
Hello!

I didn't want to create a new issue since this one (when finished) should theoretically cover the problem I've wanted to report.

The issue is about ONLY_ON_TAINTED symbolic optimization. It works well enough to clear symbolic expressions and AST nodes assigned to instructions when there is no taint. However, we have noticed that even with no taint AST nodes are being accumulated reaching high numbers on full-program analysis.

I've slightly modified Pin tracer and one of the samples to showcase the problem (at least I think it's a problem). Diff attached -- [only_on_tainted_diff.txt](https://github.com/JonathanSalwan/Triton/files/402362/only_on_tainted_diff.txt)

The output I get on `sym_only_on_tainted.py` for `crackme_xor a` is the following: 
[output.txt](https://github.com/JonathanSalwan/Triton/files/402363/output.txt)

As you can see allocated AST nodes are accumulated on memory-related operations, which seem to be in turn related to initialization of memory operands for instruction [here](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/memoryAccess.cpp#L142).

As far as I understand, since untainted symbolic expressions are freed, these untainted AST nodes are no longer needed as well. Perhaps some check for ONLY_ON_TAINTED can be used to clear these nodes right away?

Hope this helps.

**Comment by JonathanSalwan** [comment] 2016-08-05 09:22
Got it. Let me few days to fix it.

Thanks for the report.

**Comment by mermakov** [comment] 2016-08-05 13:37
Thank you for your attention!

I have been looking some more into AST allocations with ONLY_ON_TAINTED. It seems that some instructions leak a few nodes, in particular:

```
cpuid
rol reg, offs
ror reg, offs
```

Here is the diff ([diff_leak.txt](https://github.com/JonathanSalwan/Triton/files/403828/diff_leak.txt) and output ([output2.txt](https://github.com/JonathanSalwan/Triton/files/403829/output2.txt), which unfortunately includes the MemoryAccess nodes mentioned in my previous post. The instructions I've mentioned appear to leave 3 nodes hanging somewhere that are not cleared after `buildSemantics`.

I obtained the output on `crackme_xor a` rebuilt with gcc 4.9 with `-g -O0`. My system is Ubuntu 12.04 64-bit.

**Comment by mermakov** [comment] 2016-08-09 18:13
Hello, it's me again with another thing to report. This time the ONLY_ON_TAINTED started causing exceptions.

The problem is `cmpxchg` instruction with when `AX` is tainted. In this case, if we look at symbolic expressions, everything labelled with `XCHG operation` is untainted, whereas everything else is tainted (whether this is right boils down to undertainting and overtaining approach). 

However, ONLY_ON_TAINTED causes a part of AST nodes to get freed, but since symbolic expressions share some of these nodes, the tainted expressions are left with corrupted data.

Here's an a quick diff to reproduce the problem on `examples/python/ir.py`: 
[cmpxchg_diff.txt](https://github.com/JonathanSalwan/Triton/files/409614/cmpxchg_diff.txt)

This issue proposed solution (smart pointers / usage counters) will probably fix this problem as well, so I'm reporting just in case someone else runs into this problem in the meantime.

For a quick fix it is possible to avoid freeing any symbolic expressions for tainted instructions, something like this:

```
diff --git a/src/libtriton/arch/architecture.cpp b/src/libtriton/arch/architecture.cpp
index c5d0353..26cdab1 100644
--- a/src/libtriton/arch/architecture.cpp
+++ b/src/libtriton/arch/architecture.cpp
@@ -219,7 +219,8 @@ namespace triton {
        * execution only on tainted instructions, we delete all
        * expressions untainted and their AST nodes.
        */
-      if (triton::api.isSymbolicOptimizationEnabled(triton::engines::symbolic::ONLY_ON_TAINTED)) {
+      if (triton::api.isSymbolicOptimizationEnabled(triton::engines::symbolic::ONLY_ON_TAINTED) &&
+            !inst.isTainted()) {
         std::set<triton::ast::AbstractNode*> uniqueNodes;
         std::vector<triton::engines::symbolic::SymbolicExpression*> newVector;
         std::vector<triton::engines::symbolic::SymbolicExpression*>::iterator it;
```

**Comment by JonathanSalwan** [comment] 2016-08-09 20:47
@mermakov erf you're right! I really have to clean up this part of triton. Thanks for all these reports, I really appreciate. I think we should open new issues for each task.

**Comment by JonathanSalwan** [comment] 2017-07-13 14:20
PoC without allocation.

```python
from triton import *                         
                                             
ctx = TritonContext()                        
ctx.setArchitecture(ARCH.X86_64)             
ctx.enableMode(MODE.ONLY_ON_SYMBOLIZED, True)
                                             
for count in range(100000000):               
    ctx.processing(Instruction("\x00\x00"))  
    print 'count:',count                     
```

**Closed** 2018-06-05 15:03 UTC
Labels: AST Semantics Representations, Feature, libTriton
